services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/ds4:latest
    privileged: true
    command: ds4-server --rocm -m /app/models/DeepSeek-V4-Flash-IQ2XXS-w2Q2K-AProjQ8-SExpQ8-OutQ8-chat-v2-imatrix.gguf --ctx 262144 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    shm_size: 80gb
    environment:
      - HSA_XNACK=1
    volumes:
      - ./models:/app/models
    devices:
      - /dev/kfd
      - /dev/dri
